<h1><?=(empty($this->aluno->matricula)?
'Inclusão': 'Alteração')?> de Aluno</h1>

<form action="<?=$this->url('alunos',[
    'action' => 'gravar'
])?>" method="post">
    Nome: <input type="text" name="nome"
    autofocus="autofocus" 
    value="<?=$this->aluno->nome?>">
    <input type="hidden" name="matricula"
    value="<?=$this->aluno->matricula?>">
    <input type="submit" value="gravar">
</form>