<?php
?>
<h1>Cadastro de Músicas</h1>

<p>
    <a href="<?=$this->url('musicas',['action' => 'editar'])?>" class="btn btn-info">
        Incluir musica
    </a>
</p>

<h2>Musicas </h2>
<table  class="table table-striped table-dark" >
    <thead>
        <tr>
            <td width="160"><h6>Codigo</h6></td>
            <td width="105"><h6>Nome</h6></td>
            <td width="170"><h6>Artista</h6></td>
            <td width="100"><h6>Ações</h6></td>
        </tr>
    </thead>
    
    <tbody>  
              <?=$this -> partialLoop('musicas.phtml', $this -> musicas)?>    
    </tbody>
</table>


<a href="<?=$this->url('home')?>" class="btn btn-info"
>   Voltar</a>
