<h1>Cadastro de Artistas </h1>

<p><a href="<?=$this->url('artistas',[
    'action' => 'editar'
])?>" class="btn btn-info">Incluir artista</a></p>

<h2>Artistas </h2>
<table  class="table table-striped table-dark">
    <thead>
        <tr>
            <td width="165"><h6>codigo</h6></td>
            <td width="170"><h6>Nome</h6></td>
            <td width="140"><h6>Ações</h6></td>
        </tr>
    </thead>
    <tbody>
<?php echo $this->partialLoop('artistas.phtml', $this -> artistas, $this -> musicas);?>        
    </tbody>

</table>

<a href="<?=$this->url('home')?>" class="btn btn-info"
>   Voltar</a>

