
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

     <tr>
        <td width="190"><?=$this->codigo?></td> 
        <td width="170" ><?=$this->nome ?></td>   
        <td width="160"><?=$this->artista ?></td>   
        <td width="150"><a href="<?=$this->url('musicas',['action' => 'excluir', 'codigo' => $this->codigo])?>" data-confirm='Tem certeza de que deseja excluir o item selecionado?' class="btn btn-danger" style="height: 45px;">  Excluir</a> <a href="<?=$this->url('musicas',['action' => 'editar','codigo' => $this->codigo])?>" class="btn btn-warning"  style="height: 45px;">Editar</a> </td>         
     </tr>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" ></script>


<script>
$(document).ready(function(){
     $('a[data-confirm]').click(function(ev){
        var href = $(this).attr('href');
            if(!$('#confirm-delete').length){
                 $('td').append('<div class="modal fade" id="confirm-delete" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"><div class="modal-dialog"> <div class="modal-content"><div class="modal-header bg-danger text-white">EXCLUIR ITEM<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button></div><div class="text-danger" ><b>Tem certeza de que deseja excluir o item selecionando?</b></div><div class="modal-footer"><button type="button" class="btn btn-success" data-dismiss="modal">Cancelar</button><a class="btn btn-danger text-white" id="dataComfirmOK">Apagar</a></div></div></div></div>');
            }
         $('#dataComfirmOK').attr('href', href);
         $('#confirm-delete').modal({shown:true});
         return false;
    });

});

</script>

